<a href="https://colab.research.google.com/github/Quartz1605/Review-Analyser/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Natural Language Processing

## Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data_1 = pd.read_csv("/content/Restaurant_Reviews (1).tsv",delimiter='\t',quoting=3)
data_1.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

## Cleaning the texts

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,1000):
  review = re.sub('[^a-zA-Z]',' ',data_1["Review"][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
# modifying to include the word 'not' as it is included in stopwords
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,1000):
  review = re.sub('[^a-zA-Z]',' ',data_1['Review'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)





[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## Bag of words model

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
x = cv.fit_transform(corpus).toarray()
y = data_1["Liked"].values


In [ ]:
x.shape

(1000, 1500)

## Separating  into train and test

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)


## Guassian NB model

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

## Predicting and Confusion Matrix

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
confusion_matrix(y_test,y_pred)

array([[55, 42],
       [12, 91]])

In [ ]:
accuracy_score(y_test,y_pred)

0.73

## Random Forest Model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=150,criterion='entropy',random_state=0)
classifier.fit(x_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=150, random_state=0)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.78

## Predicting for Single Review

In [ ]:
corpus = []
new_review = 'I love this restaurant so much'
review = re.sub('[^a-zA-Z]',' ',new_review)
review = review.lower()
review = review.split()
review = [ps.stem(words) for words in review if not words in stopwords.words('english')]
review = ' '.join(review)
corpus.append(review)


In [ ]:
x = cv.transform(corpus).toarray()
classifier.predict(x)

array([1])

In [ ]:
corpus2 = []
new_review = 'I hate this restaurant so much'
review = re.sub('[^a-zA_Z]',' ',new_review)
review = review.lower()
review = review.split()
review = [ps.stem(words) for words in review if not words in stopwords.words('english')]
review = ' '.join(review)
corpus2.append(review)


In [ ]:
x = cv.transform(corpus2).toarray()

In [ ]:
classifier.predict(x)

array([0])

In [ ]:
corpus = []
new_review = 'I loved their noodles'
review = re.sub('[^a-zA-Z]',' ',new_review)
review = review.lower()
review = review.split()
review = [ps.stem(words) for words in review if not words in set(stopwords.words('english'))]
review = ' '.join(review)
corpus.append(review)

In [ ]:
x = cv.transform(corpus).toarray()
classifier.predict(x)

array([1])